# Generated by Django 4.2.2 on 2023-07-04 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
